### ISSUE TITLE
How to point my importmap.json?

### ISSUE THREAD

**Issue by viT-1** [Jack-Works/ttypescript-browser-like-import-transformer#30]
In [my project](https://github.com/viT-1/systemjs-ts-es6-vue/tree/038c302d760e225590fff34b80403eca6549fb5e) I forced to solve problems manually that your package solves ([js-suffix](https://github.com/viT-1/systemjs-ts-es6-vue/blob/038c302d760e225590fff34b80403eca6549fb5e/gulpfile.esm.js#L100) & [importmap-shims](https://github.com/viT-1/systemjs-ts-es6-vue/blob/038c302d760e225590fff34b80403eca6549fb5e/src/index.dev.htm#L14)).

I would like to use your package, but I don’t understand how to specify my [generated](https://github.com/viT-1/systemjs-ts-es6-vue/blob/038c302d760e225590fff34b80403eca6549fb5e/gulpfile.esm.js#L78) (needs to replace versions according package.json dependencies) importmap.json

**Comment by Jack-Works** [comment]
It is documented here. https://jack-works.github.io/ttypescript-browser-like-import-transformer/config.pluginconfigs.importmap.html
Does that help?

**Comment by Jack-Works** [comment]
import map support is experimental. Please give feedback if there is bug. thanks!
